package dashboard

import (
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/tjst-t/port-manager/internal/config"
	"github.com/tjst-t/port-manager/internal/db"
)

// Generate creates a static HTML dashboard at outputDir/index.html.
func Generate(outputDir string, leases []db.Lease, permanents []config.PermanentService, domainSuffix string) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	htmlContent := renderHTML(leases, permanents, domainSuffix)

	path := filepath.Join(outputDir, "index.html")
	if err := os.WriteFile(path, []byte(htmlContent), 0644); err != nil {
		return fmt.Errorf("writing dashboard: %w", err)
	}

	return nil
}

func renderHTML(leases []db.Lease, permanents []config.PermanentService, domainSuffix string) string {
	var b strings.Builder

	b.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>portman dashboard</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:system-ui,-apple-system,sans-serif;background:#f5f5f5;color:#333;padding:20px}
h1{margin-bottom:20px;font-size:1.5rem}
h2{margin:20px 0 10px;font-size:1.1rem;color:#555}
table{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1);margin-bottom:20px}
th,td{padding:8px 12px;text-align:left;border-bottom:1px solid #eee}
th{background:#fafafa;font-weight:600;font-size:.85rem;color:#666}
td{font-size:.9rem}
a{color:#0066cc;text-decoration:none}
a:hover{text-decoration:underline}
.active{color:#22c55e}
.stale{color:#f59e0b}
.permanent{color:#8b5cf6}
.badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:.75rem;font-weight:600}
.badge-yes{background:#dcfce7;color:#166534}
.badge-no{background:#f3f4f6;color:#6b7280}
footer{margin-top:20px;font-size:.75rem;color:#999}
</style>
</head>
<body>
<h1>portman dashboard</h1>
`)

	// Leases table
	b.WriteString(`<h2>Leases</h2>
<table>
<tr><th>Name</th><th>Project</th><th>Branch</th><th>Port</th><th>Status</th><th>Expose</th><th>Link</th></tr>
`)

	if len(leases) == 0 {
		b.WriteString(`<tr><td colspan="7" style="text-align:center;color:#999">No active leases</td></tr>`)
	}
	for _, l := range leases {
		statusIcon := `<span class="active">●</span> active`
		if l.State == "stale" {
			statusIcon = `<span class="stale">○</span> stale`
		}

		exposeBadge := `<span class="badge badge-no">no</span>`
		if l.Expose {
			exposeBadge = `<span class="badge badge-yes">yes</span>`
		}

		link := fmt.Sprintf("%d", l.Port)
		if l.Expose {
			fqdn := l.Hostname + "." + domainSuffix
			link = fmt.Sprintf(`<a href="https://%s" target="_blank">%s</a>`,
				html.EscapeString(fqdn), html.EscapeString(fqdn))
		}

		fmt.Fprintf(&b, "<tr><td>%s</td><td>%s</td><td>%s</td><td>%d</td><td>%s</td><td>%s</td><td>%s</td></tr>\n",
			html.EscapeString(l.Name),
			html.EscapeString(l.Project),
			html.EscapeString(l.Worktree),
			l.Port,
			statusIcon,
			exposeBadge,
			link,
		)
	}
	b.WriteString("</table>\n")

	// Permanent services table
	if len(permanents) > 0 {
		b.WriteString(`<h2>Permanent Services</h2>
<table>
<tr><th>Name</th><th>Port</th><th>Expose</th><th>Link</th></tr>
`)
		for _, p := range permanents {
			exposeBadge := `<span class="badge badge-no">no</span>`
			if p.Expose {
				exposeBadge = `<span class="badge badge-yes">yes</span>`
			}

			link := fmt.Sprintf("%d", p.Port)
			if p.Expose {
				fqdn := p.Name + "." + domainSuffix
				link = fmt.Sprintf(`<a href="https://%s" target="_blank">%s</a>`,
					html.EscapeString(fqdn), html.EscapeString(fqdn))
			}

			fmt.Fprintf(&b, "<tr><td><span class=\"permanent\">★</span> %s</td><td>%d</td><td>%s</td><td>%s</td></tr>\n",
				html.EscapeString(p.Name), p.Port, exposeBadge, link)
		}
		b.WriteString("</table>\n")
	}

	fmt.Fprintf(&b, `<footer>Generated by portman at %s</footer>
</body>
</html>
`, time.Now().Format("2006-01-02 15:04:05"))

	return b.String()
}
